### ISSUE TITLE
Some assets don't work in macOS and Linux Actions builds

### ISSUE THREAD

**Issue by LeWolfYT** [RHeavenStudio/HeavenStudio#243] opened 2023-01-26 21:49 UTC
it's pink

**Comment by Saraistupid** [comment] 2023-01-26 22:21
Github user read the README.md challenge (impossible)

![image](https://user-images.githubusercontent.com/37207067/214963880-05dbedfc-54a2-49f8-9685-908d971f4544.png)

**Comment by LeWolfYT** [comment] 2023-01-27 02:35
Got it!

**Comment by minenice55** [comment] 2023-01-27 03:56
leads me to think that this issue is caused by missing dependancy links when building assetbundles via autobuild, will hopefully remedy in upcoming PR

**Comment by minenice55** [comment] 2023-06-29 18:41
closed by #486

**Closed by minenice55** 2023-06-29 18:41 UTC
Labels: bug
