### ISSUE TITLE
robot barely on tap troupe

### ISSUE THREAD

**Issue by dirt-bee** [RHeavenStudio/HeavenStudio#312] opened 2023-02-22 09:46 UTC
if you makethe robot do an input on the first beat, it causes it to get a barely
![tap](https://user-images.githubusercontent.com/115891182/220583340-334e4e7b-1ac2-4072-99f0-16e84f7da25d.png)

**Comment by patataofcourse** [comment] 2023-02-22 15:16
duplicate of #274

**Closed** 2023-02-22 15:17 UTC
Labels: duplicate
